watcher:
  timer: 30s
  fsnotifier: fsnotify
  dir: /home/user/downloads
downloader:
  download_dir: /home/user/downloads
http_server:
  port: 8080
  host: localhost
  enable: true
  serve_files: true
  basic_auth: true
  basic_auth_user: toto
  basic_auth_password: tata
video:
  guesser: openguessit
  exclude_file_containing:
  - sample
  allowed_file_extensions:
  - .avi
  - .mkv
  - .mp4
  allowed_file_extensions_to_delete:
  - .srt
  - .nfo
  - .txt
  - .jpg
  - .jpeg
modules_params:
  - name: pushover
    key: sdf7as8f8ds7f9sf
    recipient: 9327a472s3947234792
  - name: addicted
    lang: fr_FR
  - name: opensubtitles
    user: opensubtitle@canapeapp.com
    lang: en_US
    password: my@w3$0m3p@$$w0rD
show:
  dir: /home/user/tvshows
  torrenters:
    - eztv
  detailers:
    - tvdb
  subtitlers:
    - addicted
movie:
  dir: /home/user/movies
  torrenters:
    - yts
  detailers:
    - tmdb
  subtitlers:
    - opensubtitles
